services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
            - /var/www/vendor
        depends_on:
            db:
                condition: service_healthy
        command: ["sh", "-c", "php artisan migrate --force && php-fpm"]
        networks:
            - laravel

    db:
        image: mysql:latest
        container_name: students_db
        restart: always
        environment:
            MYSQL_DATABASE: laravel_api
            MYSQL_ROOT_PASSWORD: 12345678
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "root",
                    "-p12345678",
                ]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 5s

    nginx:
        image: nginx:latest
        container_name: nginx_server
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

networks:
    laravel:

volumes:
    mysql_data:
